ip: 127.0.0.1
port: 12680
db_host: DB_HOST
db_port: DB_PORT
db_user: DB_USERNAME
db_password: 'DB_PASSWORD'
db_name: DB_ACCOUNT_NAME
allow_old_password: false
auto_reg: true
#allow_ips:
#  - 127.0.0.1
#  - 192.168.10.3
point_fix: 0
max_client_count: 500
pc_max_client_count: 3
